# ボットの色
botColor = "#b9d98b"
# VC操作パネルのチャンネルID
controlPanelChannelId = "000000000000000000"
# VC操作パネルのメッセージID
# (空の場合初期投稿を行います。その後この設定を投稿されたメッセージIDに書き換え、Botを再起動してください)
controlPanelMessageId = ""

# カスタムVCのチャンネルIDリスト
customVcList = [
  { channelId = "000000000000000000", maxUser = 5 }, # 1つ目のカスタムVC (人数制限5人)
  { channelId = "000000000000000000", maxUser = 0 }, # 2つ目のカスタムVC (人数制限なし)
]

# 読み上げBOTのIDリスト
readBotList = [
  { botId = "000000000000000000" }, # 1人目の読み上げBotのID
  { botId = "000000000000000000" }, # 2人目の読み上げBotのID
]